# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(default=datetime.datetime(2016, 7, 28, 14, 19, 56, 561425, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
