# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150, null=True)),
                ('main_image', models.ImageField(null=True, upload_to=None)),
                ('date_start', models.DateTimeField(null=True, verbose_name='Event Start')),
                ('date_end', models.DateTimeField(null=True, verbose_name='Event End')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Event Creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Event Update')),
                ('description', models.TextField(null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('visibility', models.BooleanField()),
                ('paying', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sold', models.IntegerField(null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.UserProfile'),
        ),
    ]
