# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:40
from __future__ import unicode_literals

from django.db import migrations
import sirtrevor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=sirtrevor.fields.SirTrevorField(),
        ),
    ]
