# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160728_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='mail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
