# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_offer',
            name='end_date',
            field=models.DateField(help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
