# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_auto_20160803_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadcv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
