# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_uploadcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='docfile',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
