# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 15:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_auto_20160809_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_offer',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
    ]
