# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 14:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_auto_20160818_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_offer',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
