# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import join.models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0011_auto_20160822_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcv',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to=join.models.upload_location),
        ),
    ]
